export type IsoCountry = {
  code: string;
  name: string;
  currency?: string;
};

export function flagEmojiFromCode(code: string): string {
  const c = code.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(c)) return "";
  const A = 0x1f1e6;
  const a = "A".charCodeAt(0);
  return String.fromCodePoint(A + c.charCodeAt(0) - a, A + c.charCodeAt(1) - a);
}

export const ISO_COUNTRIES: IsoCountry[] = [
  { code: "ad", name: "Andorra", currency: "EUR" },
  { code: "ae", name: "United Arab Emirates", currency: "AED" },
  { code: "af", name: "Afghanistan", currency: "AFN" },
  { code: "ag", name: "Antigua and Barbuda", currency: "XCD" },
  { code: "ai", name: "Anguilla", currency: "XCD" },
  { code: "al", name: "Albania", currency: "ALL" },
  { code: "am", name: "Armenia", currency: "AMD" },
  { code: "ao", name: "Angola", currency: "AOA" },
  { code: "aq", name: "Antarctica" },
  { code: "ar", name: "Argentina", currency: "ARS" },
  { code: "as", name: "American Samoa", currency: "USD" },
  { code: "at", name: "Austria", currency: "EUR" },
  { code: "au", name: "Australia", currency: "AUD" },
  { code: "aw", name: "Aruba", currency: "AWG" },
  { code: "ax", name: "Åland Islands", currency: "EUR" },
  { code: "az", name: "Azerbaijan", currency: "AZN" },
  { code: "ba", name: "Bosnia and Herzegovina", currency: "BAM" },
  { code: "bb", name: "Barbados", currency: "BBD" },
  { code: "bd", name: "Bangladesh", currency: "BDT" },
  { code: "be", name: "Belgium", currency: "EUR" },
  { code: "bf", name: "Burkina Faso", currency: "XOF" },
  { code: "bg", name: "Bulgaria", currency: "BGN" },
  { code: "bh", name: "Bahrain", currency: "BHD" },
  { code: "bi", name: "Burundi", currency: "BIF" },
  { code: "bj", name: "Benin", currency: "XOF" },
  { code: "bl", name: "Saint Barthélemy", currency: "EUR" },
  { code: "bm", name: "Bermuda", currency: "BMD" },
  { code: "bn", name: "Brunei", currency: "BND" },
  { code: "bo", name: "Bolivia", currency: "BOB" },
  { code: "bq", name: "Caribbean Netherlands", currency: "USD" },
  { code: "br", name: "Brazil", currency: "BRL" },
  { code: "bs", name: "Bahamas", currency: "BSD" },
  { code: "bt", name: "Bhutan", currency: "BTN" },
  { code: "bv", name: "Bouvet Island", currency: "NOK" },
  { code: "bw", name: "Botswana", currency: "BWP" },
  { code: "by", name: "Belarus", currency: "BYN" },
  { code: "bz", name: "Belize", currency: "BZD" },
  { code: "ca", name: "Canada", currency: "CAD" },
  { code: "cc", name: "Cocos (Keeling) Islands", currency: "AUD" },
  { code: "cd", name: "DR Congo", currency: "CDF" },
  { code: "cf", name: "Central African Republic", currency: "XAF" },
  { code: "cg", name: "Republic of the Congo", currency: "XAF" },
  { code: "ch", name: "Switzerland", currency: "CHF" },
  { code: "ci", name: "Côte d'Ivoire", currency: "XOF" },
  { code: "ck", name: "Cook Islands", currency: "NZD" },
  { code: "cl", name: "Chile", currency: "CLP" },
  { code: "cm", name: "Cameroon", currency: "XAF" },
  { code: "cn", name: "China", currency: "CNY" },
  { code: "co", name: "Colombia", currency: "COP" },
  { code: "cr", name: "Costa Rica", currency: "CRC" },
  { code: "cu", name: "Cuba", currency: "CUP" },
  { code: "cv", name: "Cape Verde", currency: "CVE" },
  { code: "cw", name: "Curaçao", currency: "ANG" },
  { code: "cx", name: "Christmas Island", currency: "AUD" },
  { code: "cy", name: "Cyprus", currency: "EUR" },
  { code: "cz", name: "Czechia", currency: "CZK" },
  { code: "de", name: "Germany", currency: "EUR" },
  { code: "dj", name: "Djibouti", currency: "DJF" },
  { code: "dk", name: "Denmark", currency: "DKK" },
  { code: "dm", name: "Dominica", currency: "XCD" },
  { code: "do", name: "Dominican Republic", currency: "DOP" },
  { code: "dz", name: "Algeria", currency: "DZD" },
  { code: "ec", name: "Ecuador", currency: "USD" },
  { code: "ee", name: "Estonia", currency: "EUR" },
  { code: "eg", name: "Egypt", currency: "EGP" },
  { code: "eh", name: "Western Sahara", currency: "MAD" },
  { code: "er", name: "Eritrea", currency: "ERN" },
  { code: "es", name: "Spain", currency: "EUR" },
  { code: "et", name: "Ethiopia", currency: "ETB" },
  { code: "fi", name: "Finland", currency: "EUR" },
  { code: "fj", name: "Fiji", currency: "FJD" },
  { code: "fk", name: "Falkland Islands", currency: "FKP" },
  { code: "fm", name: "Micronesia", currency: "USD" },
  { code: "fo", name: "Faroe Islands", currency: "DKK" },
  { code: "fr", name: "France", currency: "EUR" },
  { code: "ga", name: "Gabon", currency: "XAF" },
  { code: "gb", name: "United Kingdom", currency: "GBP" },
  { code: "gd", name: "Grenada", currency: "XCD" },
  { code: "ge", name: "Georgia", currency: "GEL" },
  { code: "gf", name: "French Guiana", currency: "EUR" },
  { code: "gg", name: "Guernsey", currency: "GBP" },
  { code: "gh", name: "Ghana", currency: "GHS" },
  { code: "gi", name: "Gibraltar", currency: "GIP" },
  { code: "gl", name: "Greenland", currency: "DKK" },
  { code: "gm", name: "Gambia", currency: "GMD" },
  { code: "gn", name: "Guinea", currency: "GNF" },
  { code: "gp", name: "Guadeloupe", currency: "EUR" },
  { code: "gq", name: "Equatorial Guinea", currency: "XAF" },
  { code: "gr", name: "Greece", currency: "EUR" },
  { code: "gs", name: "South Georgia", currency: "GBP" },
  { code: "gt", name: "Guatemala", currency: "GTQ" },
  { code: "gu", name: "Guam", currency: "USD" },
  { code: "gw", name: "Guinea-Bissau", currency: "XOF" },
  { code: "gy", name: "Guyana", currency: "GYD" },
  { code: "hk", name: "Hong Kong", currency: "HKD" },
  { code: "hm", name: "Heard & McDonald Islands", currency: "AUD" },
  { code: "hn", name: "Honduras", currency: "HNL" },
  { code: "hr", name: "Croatia", currency: "EUR" },
  { code: "ht", name: "Haiti", currency: "HTG" },
  { code: "hu", name: "Hungary", currency: "HUF" },
  { code: "id", name: "Indonesia", currency: "IDR" },
  { code: "ie", name: "Ireland", currency: "EUR" },
  { code: "il", name: "Israel", currency: "ILS" },
  { code: "im", name: "Isle of Man", currency: "GBP" },
  { code: "in", name: "India", currency: "INR" },
  { code: "io", name: "British Indian Ocean Territory", currency: "USD" },
  { code: "iq", name: "Iraq", currency: "IQD" },
  { code: "ir", name: "Iran", currency: "IRR" },
  { code: "is", name: "Iceland", currency: "ISK" },
  { code: "it", name: "Italy", currency: "EUR" },
  { code: "je", name: "Jersey", currency: "GBP" },
  { code: "jm", name: "Jamaica", currency: "JMD" },
  { code: "jo", name: "Jordan", currency: "JOD" },
  { code: "jp", name: "Japan", currency: "JPY" },
  { code: "ke", name: "Kenya", currency: "KES" },
  { code: "kg", name: "Kyrgyzstan", currency: "KGS" },
  { code: "kh", name: "Cambodia", currency: "KHR" },
  { code: "ki", name: "Kiribati", currency: "AUD" },
  { code: "km", name: "Comoros", currency: "KMF" },
  { code: "kn", name: "Saint Kitts and Nevis", currency: "XCD" },
  { code: "kp", name: "North Korea", currency: "KPW" },
  { code: "kr", name: "South Korea", currency: "KRW" },
  { code: "kw", name: "Kuwait", currency: "KWD" },
  { code: "ky", name: "Cayman Islands", currency: "KYD" },
  { code: "kz", name: "Kazakhstan", currency: "KZT" },
  { code: "la", name: "Laos", currency: "LAK" },
  { code: "lb", name: "Lebanon", currency: "LBP" },
  { code: "lc", name: "Saint Lucia", currency: "XCD" },
  { code: "li", name: "Liechtenstein", currency: "CHF" },
  { code: "lk", name: "Sri Lanka", currency: "LKR" },
  { code: "lr", name: "Liberia", currency: "LRD" },
  { code: "ls", name: "Lesotho", currency: "LSL" },
  { code: "lt", name: "Lithuania", currency: "EUR" },
  { code: "lu", name: "Luxembourg", currency: "EUR" },
  { code: "lv", name: "Latvia", currency: "EUR" },
  { code: "ly", name: "Libya", currency: "LYD" },
  { code: "ma", name: "Morocco", currency: "MAD" },
  { code: "mc", name: "Monaco", currency: "EUR" },
  { code: "md", name: "Moldova", currency: "MDL" },
  { code: "me", name: "Montenegro", currency: "EUR" },
  { code: "mf", name: "Saint Martin", currency: "EUR" },
  { code: "mg", name: "Madagascar", currency: "MGA" },
  { code: "mh", name: "Marshall Islands", currency: "USD" },
  { code: "mk", name: "North Macedonia", currency: "MKD" },
  { code: "ml", name: "Mali", currency: "XOF" },
  { code: "mm", name: "Myanmar", currency: "MMK" },
  { code: "mn", name: "Mongolia", currency: "MNT" },
  { code: "mo", name: "Macau", currency: "MOP" },
  { code: "mp", name: "Northern Mariana Islands", currency: "USD" },
  { code: "mq", name: "Martinique", currency: "EUR" },
  { code: "mr", name: "Mauritania", currency: "MRU" },
  { code: "ms", name: "Montserrat", currency: "XCD" },
  { code: "mt", name: "Malta", currency: "EUR" },
  { code: "mu", name: "Mauritius", currency: "MUR" },
  { code: "mv", name: "Maldives", currency: "MVR" },
  { code: "mw", name: "Malawi", currency: "MWK" },
  { code: "mx", name: "Mexico", currency: "MXN" },
  { code: "my", name: "Malaysia", currency: "MYR" },
  { code: "mz", name: "Mozambique", currency: "MZN" },
  { code: "na", name: "Namibia", currency: "NAD" },
  { code: "nc", name: "New Caledonia", currency: "XPF" },
  { code: "ne", name: "Niger", currency: "XOF" },
  { code: "nf", name: "Norfolk Island", currency: "AUD" },
  { code: "ng", name: "Nigeria", currency: "NGN" },
  { code: "ni", name: "Nicaragua", currency: "NIO" },
  { code: "nl", name: "Netherlands", currency: "EUR" },
  { code: "no", name: "Norway", currency: "NOK" },
  { code: "np", name: "Nepal", currency: "NPR" },
  { code: "nr", name: "Nauru", currency: "AUD" },
  { code: "nu", name: "Niue", currency: "NZD" },
  { code: "nz", name: "New Zealand", currency: "NZD" },
  { code: "om", name: "Oman", currency: "OMR" },
  { code: "pa", name: "Panama", currency: "PAB" },
  { code: "pe", name: "Peru", currency: "PEN" },
  { code: "pf", name: "French Polynesia", currency: "XPF" },
  { code: "pg", name: "Papua New Guinea", currency: "PGK" },
  { code: "ph", name: "Philippines", currency: "PHP" },
  { code: "pk", name: "Pakistan", currency: "PKR" },
  { code: "pl", name: "Poland", currency: "PLN" },
  { code: "pm", name: "Saint Pierre and Miquelon", currency: "EUR" },
  { code: "pn", name: "Pitcairn Islands", currency: "NZD" },
  { code: "pr", name: "Puerto Rico", currency: "USD" },
  { code: "ps", name: "Palestine", currency: "ILS" },
  { code: "pt", name: "Portugal", currency: "EUR" },
  { code: "pw", name: "Palau", currency: "USD" },
  { code: "py", name: "Paraguay", currency: "PYG" },
  { code: "qa", name: "Qatar", currency: "QAR" },
  { code: "re", name: "Réunion", currency: "EUR" },
  { code: "ro", name: "Romania", currency: "RON" },
  { code: "rs", name: "Serbia", currency: "RSD" },
  { code: "ru", name: "Russia", currency: "RUB" },
  { code: "rw", name: "Rwanda", currency: "RWF" },
  { code: "sa", name: "Saudi Arabia", currency: "SAR" },
  { code: "sb", name: "Solomon Islands", currency: "SBD" },
  { code: "sc", name: "Seychelles", currency: "SCR" },
  { code: "sd", name: "Sudan", currency: "SDG" },
  { code: "se", name: "Sweden", currency: "SEK" },
  { code: "sg", name: "Singapore", currency: "SGD" },
  { code: "sh", name: "Saint Helena", currency: "SHP" },
  { code: "si", name: "Slovenia", currency: "EUR" },
  { code: "sj", name: "Svalbard and Jan Mayen", currency: "NOK" },
  { code: "sk", name: "Slovakia", currency: "EUR" },
  { code: "sl", name: "Sierra Leone", currency: "SLE" },
  { code: "sm", name: "San Marino", currency: "EUR" },
  { code: "sn", name: "Senegal", currency: "XOF" },
  { code: "so", name: "Somalia", currency: "SOS" },
  { code: "sr", name: "Suriname", currency: "SRD" },
  { code: "ss", name: "South Sudan", currency: "SSP" },
  { code: "st", name: "São Tomé and Príncipe", currency: "STN" },
  { code: "sv", name: "El Salvador", currency: "USD" },
  { code: "sx", name: "Sint Maarten", currency: "ANG" },
  { code: "sy", name: "Syria", currency: "SYP" },
  { code: "sz", name: "Eswatini", currency: "SZL" },
  { code: "tc", name: "Turks and Caicos Islands", currency: "USD" },
  { code: "td", name: "Chad", currency: "XAF" },
  { code: "tf", name: "French Southern Territories", currency: "EUR" },
  { code: "tg", name: "Togo", currency: "XOF" },
  { code: "th", name: "Thailand", currency: "THB" },
  { code: "tj", name: "Tajikistan", currency: "TJS" },
  { code: "tk", name: "Tokelau", currency: "NZD" },
  { code: "tl", name: "Timor-Leste", currency: "USD" },
  { code: "tm", name: "Turkmenistan", currency: "TMT" },
  { code: "tn", name: "Tunisia", currency: "TND" },
  { code: "to", name: "Tonga", currency: "TOP" },
  { code: "tr", name: "Turkey", currency: "TRY" },
  { code: "tt", name: "Trinidad and Tobago", currency: "TTD" },
  { code: "tv", name: "Tuvalu", currency: "AUD" },
  { code: "tw", name: "Taiwan", currency: "TWD" },
  { code: "tz", name: "Tanzania", currency: "TZS" },
  { code: "ua", name: "Ukraine", currency: "UAH" },
  { code: "ug", name: "Uganda", currency: "UGX" },
  { code: "um", name: "U.S. Outlying Islands", currency: "USD" },
  { code: "us", name: "United States", currency: "USD" },
  { code: "uy", name: "Uruguay", currency: "UYU" },
  { code: "uz", name: "Uzbekistan", currency: "UZS" },
  { code: "va", name: "Vatican City", currency: "EUR" },
  { code: "vc", name: "Saint Vincent and the Grenadines", currency: "XCD" },
  { code: "ve", name: "Venezuela", currency: "VES" },
  { code: "vg", name: "British Virgin Islands", currency: "USD" },
  { code: "vi", name: "U.S. Virgin Islands", currency: "USD" },
  { code: "vn", name: "Vietnam", currency: "VND" },
  { code: "vu", name: "Vanuatu", currency: "VUV" },
  { code: "wf", name: "Wallis and Futuna", currency: "XPF" },
  { code: "ws", name: "Samoa", currency: "WST" },
  { code: "ye", name: "Yemen", currency: "YER" },
  { code: "yt", name: "Mayotte", currency: "EUR" },
  { code: "za", name: "South Africa", currency: "ZAR" },
  { code: "zm", name: "Zambia", currency: "ZMW" },
  { code: "zw", name: "Zimbabwe", currency: "ZWL" },
];

export function findIsoCountry(code: string): IsoCountry | undefined {
  const c = code.toLowerCase().trim();
  return ISO_COUNTRIES.find((x) => x.code === c);
}
